config/routes.rb
Rails.application.routes.draw do

  resources :violations

  get "manhattan" => 'violations#manhattan'
  get "bronx" => 'violations#bronx'
  get "brooklyn" => 'violations#brooklyn'

  root 'welcome#index'

end

app/models/violation.rb
class Violation < ActiveRecord::Base


  def self.get_sunburst_data(boro_id)

   Violation.where("boro_id = ?", boro_id).group_by { |v| v.keyword }.map do |keyword, violations|
        {
          name: keyword,
          children: violations.group_by{ |v| v.subcat }.map do |subcat, violations|
            {
              name: subcat,
              count: violations.count
            }
          end
        }
      end

  end

  def self.get_bar_chart_data(boro_id)
     Violation.where("boro_id = ?", boro_id).group_by { |v| v.keyword }.map do |keyword, violations|
        {keyword: keyword, value: violations.count}
      end

  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController

  def index
    gon.man_data = Violation.get_bar_chart_data(1)
    gon.bx_data = Violation.get_bar_chart_data(2)
    gon.bk_data = Violation.get_bar_chart_data(3)
  end

  def manhattan
    gon.man_data = Violation.get_bar_chart_data(1)
    gon.man_sunburst_data = Violation.get_sunburst_data(1)
  end

  def bronx
    gon.bx_data = Violation.get_bar_chart_data(2)
    gon.bx_sunburst_data = Violation.get_sunburst_data(2)

  end

  def brooklyn
    gon.bk_data = Violation.get_bar_chart_data(3)
    gon.bk_sunburst_data = Violation.get_sunburst_data(3)

  end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NychaRepairCharts</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">NYCHA Repair Charts</a>
    </div>

    <div class="collapse navbar-collapse" id="primary_nav_wrap">
      <ul class="nav navbar-nav">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Boro<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/manhattan">Manhattan</a></li>
            <li><a href="/brooklyn">Brooklyn</a></li>
            <li><a href="/bronx">Bronx</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/violations/_bk_bar.html.erb
<h4 class="chart-heading col-md-offset-4">Brooklyn Repair Issues by Type:</h3>
<svg class="bk-chart col-md-offset-1"></svg><br><br><br>
<script type="text/javascript">

$(document).ready(renderChart(gon.bk_data, ".bk-chart"));</script>

app/views/violations/_bk_burst.html.erb
<h4 class="chart-heading col-md-offset-5">Subcategories:</h3><br>
<div class="bk-burst"></div>

app/views/violations/_bx_bar.html.erb
<h4 class="chart-heading col-md-offset-4">Bronx Repair Issues by Type:</h3>

<svg class="bx-chart col-md-offset-1"></svg><br><br><br>

app/views/violations/_bx_burst.html.erb
<h4 class="chart-heading col-md-offset-5">Subcategories:</h3><br>
<div class="bx-burst"></div>

app/views/violations/_manhattan_bar.html.erb
<h4 class="chart-heading col-md-offset-4">Manhattan Repair Issues by Type:</h3>
<svg class="man-chart col-md-offset-1"></svg><br><br><br>
<script type="text/javascript">
renderChart(gon.man_data, ".man-chart");</script>

app/views/violations/_manhattan_burst.html.erb
<h4 class="chart-heading col-md-offset-5">Subcategories:</h3><br>
<div class="man-burst"></div>

app/views/violations/bronx.html.erb
<%= render partial: "bx_bar"%>
<%= render partial: "bx_burst"%>

app/views/violations/brooklyn.html.erb
<%= render partial: "bk_bar"%>
<%= render partial: "bk_burst"%>

app/views/violations/index.html.erb
<%= render partial: "manhattan_bar"%>
<div class="col-md-offest-4">
<a href="/manhattan"><button class="btn btn-primary index-btn">See Breakdown</button></a>
</div><br>

<%= render partial: "bx_bar"%>
<div class="col-md-offest-4">
<a href="/bronx"><button class="btn btn-primary index-btn">See Breakdown</button></a>
</div><br>
<%= render partial: "bk_bar"%>
<div class="col-md-offest-4">
<a href="/brooklyn"><button class="btn btn-primary index-btn">See Breakdown</button></a>
</div><br>

<!-- <h4 class="chart-heading col-md-offset-4">Manhattan Repair Issues by Type:</h3>
<svg class="chart col-md-offset-1"></svg><br><br><br>
<a href="/manhattan"><button>More</button></a>
<h4 class="chart-heading col-md-offset-4">Brooklyn Repair Issues by Type:</h3>

<h4 class="chart-heading col-md-offset-5">Subcategories:</h3><br>
 <svg class="sunburst col-md-offset-3"></svg> --> 

app/views/violations/manhattan.html.erb
<%= render partial: "manhattan_bar"%>
<%= render partial: "manhattan_burst"%>




<!-- <svg class="sunburst col-md-offset-3"></svg> -->

app/views/welcome/index.html.erb
<div class="landing-page">
  <p class="well well-lg col-md-8 col-md-offset-2 text-center">NYCHA needs $6 billion dollars for capital improvement work which includes: brick work, façade and roof repairs, elevator replacement, front and rear entrance renovations, heating upgrades and kitchen and bathroom renovations.<br><br>Learn more about these repair issues:</p>

</div><br>
<div class= "col-md-8 col-md-offset-2 text-center">
<a href="<%=violations_path%>"><button class="btn btn-default">view charts</button></a>
</div>